version: '3.8'

services:
  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "7000:6379"
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000"]
    volumes:
      - redis1-data:/data

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "7001:6379"
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000"]
    volumes:
      - redis2-data:/data

  redis3:
    image: redis:latest
    container_name: redis3
    ports:
      - "7002:6379"
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000"]
    volumes:
      - redis3-data:/data

volumes:
  redis1-data:
  redis2-data:
  redis3-data:
